/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p1_lfp.automata.editar;

import com.mycompany.p1_lfp.buscar.Buscar;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author huron_clinch
 */
public class EditarFrontend extends javax.swing.JFrame {

    private final EditarBackend BACKEND = new EditarBackend(this);

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarFrontend.class.getName());

    /**
     * Creates new form EditarFrontend
     */
    public EditarFrontend(String TEXT) {
        initComponents();
        textoPanel.setText(TEXT);//Definir el tenxto en cuadro entre pestanas
        textoPanel.setPreferredSize(new Dimension(400, 200));
        setResizable(false);
        setLocationRelativeTo(null);
        setSize(1330, 715);
        BACKEND.colorear();//Generar funcion para accion
        BACKEND.analizarTexto();//Analizar si hay tento
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoPanel = new javax.swing.JTextPane();
        BtReporteToken = new javax.swing.JButton();
        BtReporteErrores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtGenerarAutomata = new javax.swing.JButton();
        BtDiagramaTransiciones = new javax.swing.JButton();
        textoBusqueda = new javax.swing.JTextField();
        BtBuscar = new javax.swing.JButton();
        BtBuscar1 = new javax.swing.JButton();
        BtBuscar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        VisorMovimientos = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(889, 645));
        jPanel1.setMinimumSize(new java.awt.Dimension(889, 645));
        jPanel1.setName(""); // NOI18N

        textoPanel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        textoPanel.setMaximumSize(new java.awt.Dimension(62, 26));
        jScrollPane1.setViewportView(textoPanel);

        BtReporteToken.setText("Reporte Token");
        BtReporteToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtReporteTokenActionPerformed(evt);
            }
        });

        BtReporteErrores.setText("Reporte Errores");
        BtReporteErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtReporteErroresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Consola Analizador lexico");

        BtGenerarAutomata.setText("Generar Automata");
        BtGenerarAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGenerarAutomataActionPerformed(evt);
            }
        });

        BtDiagramaTransiciones.setText("Diagrama de Transiciones");
        BtDiagramaTransiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDiagramaTransicionesActionPerformed(evt);
            }
        });

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        BtBuscar1.setText("Limpiar");
        BtBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscar1ActionPerformed(evt);
            }
        });

        BtBuscar2.setText("Buscar");
        BtBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(216, 216, 216)
                                .addComponent(BtBuscar2)
                                .addGap(161, 161, 161))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtReporteToken, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtReporteErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtGenerarAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtDiagramaTransiciones))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtBuscar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(textoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtBuscar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscar)
                    .addComponent(BtBuscar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtReporteToken)
                    .addComponent(BtReporteErrores)
                    .addComponent(BtGenerarAutomata)
                    .addComponent(BtDiagramaTransiciones))
                .addContainerGap())
        );

        VisorMovimientos.setFocusable(false);
        jScrollPane2.setViewportView(VisorMovimientos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtReporteTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtReporteTokenActionPerformed
        this.setVisible(false);
        BACKEND.mostrarReporteTokens();
    }//GEN-LAST:event_BtReporteTokenActionPerformed

    private void BtReporteErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtReporteErroresActionPerformed
        this.setVisible(false);
        BACKEND.mostrarReporteErrores();
    }//GEN-LAST:event_BtReporteErroresActionPerformed

    private void BtGenerarAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGenerarAutomataActionPerformed
        String contenido = textoPanel.getText();//Obtener contenido de panel
        System.out.println(contenido);
    }//GEN-LAST:event_BtGenerarAutomataActionPerformed

    private void BtDiagramaTransicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDiagramaTransicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtDiagramaTransicionesActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        BACKEND.buscarPatron();
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void BtBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscar1ActionPerformed
        textoPanel.getHighlighter().removeAllHighlights();
    }//GEN-LAST:event_BtBuscar1ActionPerformed

    private void BtBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtBuscar2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtBuscar1;
    private javax.swing.JButton BtBuscar2;
    private javax.swing.JButton BtDiagramaTransiciones;
    private javax.swing.JButton BtGenerarAutomata;
    private javax.swing.JButton BtReporteErrores;
    private javax.swing.JButton BtReporteToken;
    private javax.swing.JTextPane VisorMovimientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textoBusqueda;
    private javax.swing.JTextPane textoPanel;
    // End of variables declaration//GEN-END:variables

    public JTextPane getTextoPanel() {
        return textoPanel;
    }

    public JTextPane getVisorMovimientos() {
        return VisorMovimientos;
    }

    public JTextField getTextoBusqueda() {
        return textoBusqueda;
    }

}
